### PR TITLE
mango to report on static evasion tactics

### PR DESCRIPTION
**Pull request by erev0s**
This PR offers in mango the possibility
 - to handle APKs that employ static analysis evasion methods,
 - to report, during an import, whether a static analysis evasion method was used or not. 

Given that mango utilizes androguard to gather statically information about apks and due to it is used often against malware and static analysis evasion is a feature employed by packers, i believe it would be a nice addition if it would report also whether an apk has employed methods for evading static analysis. 

The following two snippets show two examples, the first using [this](https://www.joesandbox.com/analysis/1344544) malware and the second showing a normal app.

~~~~
[------------------------------------Package Details---------------------------------------]:
|    Original Filename :/path/to/infected.apk
|    Application Name  :로젠택배
|    Package Name      :wyija.utykuvr.uwpexgh
|    Version code      :1
|    Version Name      :17.1.22
|    Mimimum SDK       :15
|    Target  SDK       :21
|    Max SDK           :None
|    Sha256            :b3561bf581721c84fd92501e2d0886b284e8fa8e7dc193e41ab300a063dfe5f3
|    Debuggable        :false
|    Allow Backup      :true
|    Evasion Tactics   :ZIP | MANIFEST
[------------------------------------------------------------------------------------------]
~~~~

~~~~
[------------------------------------Package Details---------------------------------------]:
|    Original Filename :./minimal_orig.apk
|    Application Name  :erev0s.com - Minimal
|    Package Name      :com.erev0s.minimal
|    Version code      :1
|    Version Name      :1.0
|    Mimimum SDK       :24
|    Target  SDK       :33
|    Max SDK           :None
|    Sha256            :e6e53d117986317d2c70b8ce253d02449df1b269097bc51113522d0be47128a7
|    Debuggable        :None
|    Allow Backup      :true
|    Evasion Tactics   :None
[------------------------------------------------------------------------------------------]
~~~~

Notice the `Evasion Tactics` field.

This capability is possible through [apkInspector](https://github.com/erev0s/apkInspector) (more info [here](https://erev0s.com/blog/unmasking-evasive-threats-with-apkinspector/)), which is now part of [androguard](https://github.com/androguard/androguard/commit/1a30cbabeccdf828c3ccee4b21276d997c78abc8)

Something to consider before merging is that due to androguard does not have a proper streamlined process for releases into PyPI yet ([I am working on that](https://github.com/androguard/androguard/pull/957)), I have added in the requirements the dependency based on a specific commit. In the future, once androguard releases a new version into PyPI, we can update it.

Please let me know if there any suggested edits/updates.

### CODE REVIEW

**Comment by Ch0pin** [comment]
Thank you @erev0s , let me check this out and get back to you.

**Comment by Ch0pin** [comment]
@erev0s , there seems to be a "noisy" debug output, that probably has to do with Androguard:

Screenshot 2023-11-30 at 09 32 21

Also, the "application name " field , if I am not mistaken displays the string reference rather than the string itself.

**Comment by erev0s** [comment]
### For the pretty verbose output
This has to do with the hardcoded 'INFO' [here](https://github.com/androguard/androguard/blob/master/androguard/util.py#L16). Its something that annoyed me as well, will do a PR, hopefully somewhere in the next weeks to get this verbose output only when intended.


### For the application name
[Here](https://github.com/androguard/androguard/blob/master/androguard/core/apk/__init__.py#L450) you can see how androguard retrieves the application name. [Here](https://i.imgur.com/mflFmmw.jpg) is a similar example to the application you showed above where it cannot be resolved and in comparison i have used both version 3.3.5 and the latest and they both end up with the same output. [Here](https://i.imgur.com/WMEnEDf.png) is the analysis with mango.

The reason behind it is due to the value of the label is marked as a [reference](https://i.imgur.com/mRrbh1o.png) and it was not found. The same result is for other [tools](https://i.imgur.com/s2cXFjj.png) as well.

**Comment by Ch0pin** [comment]
@erev0s , sorry about the delay, I was out of office. 

I am not sure about the application name , this is the entry in the manifest (as decompiled with jadx) 

   android:label="@string/application_name"

3.3.5 Gives the right value:

````
[------------------------------------Package Details---------------------------------------]:
|    Original Filename :base.apk
|    Application Name  :Airbnb
|    Package Name      :com.airbnb.android
|    Version code      :28002160
|    Version Name      :23.47
|    Mimimum SDK       :28
|    Target  SDK       :33
|    Max SDK           :None
|    Sha256            :55333e0f0db46087dae8b923bc5acd78ca780ac88a60be717cead3fee13122d3
|    Debuggable        :None
|    Allow Backup      :true
[------------------------------------------------------------------------------------------]
````
Actually I checked a 2nd apk and I am getting the same result (3.3.5 returns the actual value):

````
[------------------------------------Package Details---------------------------------------]:                                                                                                                                                   
|    Original Filename :ww.apk                                                                                                                                                                                                                  
|    Application Name  :@7F13025E                                                                                                                                                                                                               
|    Package Name      :com.weightwatchers.mobile                                                                                                                                                                                               
|    Version code      :903687                                                                                                                                                                                                                  
|    Version Name      :10.51.1                                                                                                                                                                                                                 
|    Mimimum SDK       :24                                                                                                                                                                                                                      
|    Target  SDK       :34                                                                                                                                                                                                                      
|    Max SDK           :None                                                                                                                                                                                                                    
|    Sha256            :5d5ae257d4308dcd3092a4046fad115e4e5bcbd3bbd6b1606297cf8b264e323d                                                                                                                                                        
|    Debuggable        :None                                                                                                                                                                                                                    
|    Allow Backup      :false                                                                                                                                                                                                                   
|    Evasion Tactics   :None                                                                                                                                                                                                                    
[------------------------------------------------------------------------------------------]        
```

**Comment by erev0s** [comment]
@Ch0pin thank you for insisting in checking this more, as I moved past it thinking it was just the reference missing.
After some digging it turns out it is a tricky bug introduced to Androguard from a commit almost a year ago.

The PR https://github.com/androguard/androguard/pull/960 is awaiting. That should be able to fix this issue.

**Comment by Ch0pin** [comment]
@erev0s , this addition is very interesting and I would like to see it in mango, but there are some issues that have to be fixed. I am closing this for now, please let me know if you have any progress.

**Pull request closed without merging**
