### PR TITLE
Add patchmultiple functionality to patch bundled apks

### PR DESCRIPTION
**Pull request by alright21**
This pull request solves #85, completing pull request https://github.com/Ch0pin/medusa/pull/86.

In this pull request I created the possibility to patch all the apks from a bundled app. We can use it when we have the base.apk and all the split_config. apks.
- for code reusability, I created an internal method `patch_apk` that takes a str, and I use it in both `do_patch` and `do_patchmultiple`. 
- I also added autocompletion of file arguments, to make it easier to write the file names
- when decompiling the apk, I create a single directory for each apk, in other to split all the files accordingly
- I used colorama library, and fixed some typos

Further discussion:
- I was thinking if it is necessary to have a new command or just implement `do_patch` that iterates over `arg_list`. Let me know your preferred solution
- when backing up the original, maybe it is better to keep the original apk with the initial name, and create the patched apk with an `_debuggable` extension. What do you think is the best solution? In the latter case, I can work on that.

### CODE REVIEW

**Comment by Ch0pin** [comment]
@alright21 , besides the fact that I am switching to a logger in order to handle the output, it seems fine.

**Comment by alright21** [comment]
Thanks for the feedback. So I will keep the commands separated. I am also trying to find a fix for when you call patch using a full path, because it gives an error since it can't find the proper file during backup. 
Moreover, I was wondering if it is better to keep the original apk file with the original name, and the patched one with another name (e.g. patched_app.apk), in order to keep the original file clean (maybe you have some suggestions on which solution is better).
Finally, for the logger: I will wait for some example and then I can contribute to refactor the code

**Comment by Ch0pin** [comment]
> So I will keep the commands separated. 

I guess you mean to patch a single or multiple apks. Yes, it is better to keep the commands separated or add an option to the do_patch. 

```
For example:

mango>patch /full/path/to/apk.apk

or

patch -m  /full/path/to/apk1.apk <> /full/path/to/apk2.apk < > /full/path/to/apk3.apk 

where <> can be space, or maybe a separator character like coma.
```

In this case, it is better to create two different methods to handle the flows, having the do_patch as the main one which calls the corresponding method depending on the arguments.

>Moreover, I was wondering if it is better to keep the original apk file with the original name, and the patched one with another name (e.g. patched_app.apk), in order to keep the original file clean (maybe you have some suggestions on which solution is better).

Definitely yes,  we need to keep the original apk as it is.

>Finally, for the logger: I will wait for some example and then I can contribute to refactor the code

Not a problem, I can add it myself. Just trying to tide up few things and I need to sync the output format across the scripts. Example:

```python
logger.info("Attempting to download the file...")
...
logger.error("Download Failed !")

````

**Comment by alright21** [comment]
I have added the following changes:
- I kept the original file with the original filename. The debuggable file will be renamed as `_debuggable` (e.g. `app_debuggable.apk`)
- I added `logger.` in `do_patch` and `do_patchmultiple`

For now, I will keep two commands separated (patch and patchmultiple), but we can refactor the code and modify commands installmultiple, pullmultiple and patchmultiple in another pull-request so that they will use the original commands (`install`, `pull`, `patch`) and a flag `-m` instead suffix `multiple` (which splits in two separate `do_`).

From my side this modification is over, let me know if you need further changes or you can merge it :)

**Comment by alright21** [comment]
I will add that this pull request resolves #85

**Comment by Ch0pin** [comment]
Thank you very much @alright21

**Pull request merged**
